version: "3.4"

services:
  media-server:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    restart: always
    environment:
      - VITE_PORT=${PORT}
    ports:
      - "${PORT}:8080"
    volumes:
      - ./media:/usr/src/app/media
      - type: bind
        source: ./users.json
        target: /usr/src/app/users.json
      - type: bind
        source: ./user-settings.json
        target: /usr/src/app/user-settings.json
